#!/bin/sh
set -e

# Check if full CPU setup has been completed (sentinel file).
# The GPU proving key only has *.consttree_gpu files; CPU proving also needs
# *.consttree files for all stages (air, compressor, recursive1, recursive2,
# vadcop_final), generated by: cargo-zisk check-setup -a --proving-key <key>
SENTINEL="${PROVING_KEY_PATH}/.cpu-setup-complete"

if [ ! -f "$SENTINEL" ]; then
    echo "CPU consttree files incomplete. Running check-setup -a (runs once, may take a few minutes)..."
    cargo-zisk check-setup -a --proving-key "$PROVING_KEY_PATH"
    touch "$SENTINEL"
    echo "check-setup complete."
fi

exec /app/davinci-zkvm
