//! BabyJubJub in circomlib twisted Edwards form: `a*x^2 + y^2 = 1 + d*x^2*y^2`,
//! `a = 168700`, `d = 168696`, generator B8. This is the form the guest and the
//! circom ballot circuit use; the gnark reduced form (RTE) only appears inside
//! the Chaum-Pedersen Fiat-Shamir hash.

use ark_ff::{BigInteger, Field, MontFp, PrimeField};
use serde::{Deserialize, Deserializer, Serialize, Serializer};

use super::field::{fr_from_be, fr_to_be, Fr, U256};
use crate::Error;

const A: Fr = MontFp!("168700");
const D: Fr = MontFp!("168696");
const B8X: Fr =
    MontFp!("5299619240641551281634865583518297030282874472190772894086521144482721001553");
const B8Y: Fr =
    MontFp!("16950150798460657717958625567821834550301663161624707787222815936182638968203");
/// `-f mod p`, f = the gnark/iden3 scaling factor
/// 6360561867910373094066688120553762416144456282423235903351243436111059670888.
/// `x_rte = x_te * (-f)`.
const NEG_F: Fr =
    MontFp!("15527681003928902128179717624703512672403908117992798440346960750464748824729");

/// Order `l` of the prime-order subgroup generated by B8 (curve order = 8*l).
pub const SUBGROUP_ORDER: U256 = ark_ff::BigInt([
    0x677297dc392126f1,
    0xab3eedb83920ee0a,
    0x370a08b6d0302b0b,
    0x060c89ce5c263405,
]);

/// Affine TE point. Constructors in this module keep coordinates canonical and
/// on the curve; a hand-built value is only as valid as its inputs.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct Point {
    pub x: Fr,
    pub y: Fr,
}

// Extended coordinates (X:Y:T:Z), x = X/Z, y = Y/Z, T = XY/Z.
#[derive(Clone, Copy)]
struct Ext {
    x: Fr,
    y: Fr,
    t: Fr,
    z: Fr,
}

impl Ext {
    const IDENTITY: Ext = Ext {
        x: Fr::ZERO,
        y: Fr::ONE,
        t: Fr::ZERO,
        z: Fr::ONE,
    };

    fn from_affine(p: &Point) -> Ext {
        Ext {
            x: p.x,
            y: p.y,
            t: p.x * p.y,
            z: Fr::ONE,
        }
    }

    // add-2008-hwcd, complete on this curve (a square, d non-square).
    fn add(&self, o: &Ext) -> Ext {
        let a = self.x * o.x;
        let b = self.y * o.y;
        let c = D * self.t * o.t;
        let d = self.z * o.z;
        let e = (self.x + self.y) * (o.x + o.y) - a - b;
        let f = d - c;
        let g = d + c;
        let h = b - A * a;
        Ext {
            x: e * f,
            y: g * h,
            t: e * h,
            z: f * g,
        }
    }

    // dbl-2008-hwcd.
    fn double(&self) -> Ext {
        let a = self.x.square();
        let b = self.y.square();
        let c = self.z.square().double();
        let d = A * a;
        let e = (self.x + self.y).square() - a - b;
        let g = d + b;
        let f = g - c;
        let h = d - b;
        Ext {
            x: e * f,
            y: g * h,
            t: e * h,
            z: f * g,
        }
    }

    fn to_affine(self) -> Point {
        // z never vanishes for points on the curve (complete law).
        let zinv = self.z.inverse().unwrap_or(Fr::ZERO);
        Point {
            x: self.x * zinv,
            y: self.y * zinv,
        }
    }
}

impl Point {
    pub const IDENTITY: Point = Point {
        x: Fr::ZERO,
        y: Fr::ONE,
    };

    /// The iden3 base point B8, generator of the prime-order subgroup.
    pub fn generator() -> Point {
        Point { x: B8X, y: B8Y }
    }

    pub fn add(&self, o: &Point) -> Point {
        Ext::from_affine(self).add(&Ext::from_affine(o)).to_affine()
    }

    /// Group inverse `(-x, y)`.
    pub fn neg(&self) -> Point {
        Point {
            x: -self.x,
            y: self.y,
        }
    }

    pub fn sub(&self, o: &Point) -> Point {
        self.add(&o.neg())
    }

    /// `k * self` over the full 256-bit scalar, unreduced (same group element
    /// as reducing mod the point order, like the guest's `bjj_mul`).
    pub fn mul(&self, k: &U256) -> Point {
        let base = Ext::from_affine(self);
        let mut acc = Ext::IDENTITY;
        for i in (0..k.num_bits() as usize).rev() {
            acc = acc.double();
            if k.get_bit(i) {
                acc = acc.add(&base);
            }
        }
        acc.to_affine()
    }

    pub fn is_on_curve(&self) -> bool {
        let x2 = self.x.square();
        let y2 = self.y.square();
        A * x2 + y2 == Fr::ONE + D * x2 * y2
    }

    /// On the curve and `l * P = O`. The identity passes; callers that need a
    /// usable key must reject it separately.
    pub fn in_subgroup(&self) -> bool {
        self.is_on_curve() && self.mul(&SUBGROUP_ORDER) == Point::IDENTITY
    }

    /// `BE32(y + ((x & 1) << 254))`, the DA blob point encoding. Identity -> 1.
    pub fn compress(&self) -> [u8; 32] {
        let mut out = fr_to_be(&self.y);
        if self.x.into_bigint().is_odd() {
            out[0] |= 0x40;
        }
        out
    }

    /// Inverse of [`Point::compress`]. Rejects a set top bit, `y >= p`, a
    /// non-residue `x^2`, and `x = 0` with the parity bit set.
    pub fn decompress(c: &[u8; 32]) -> Result<Point, Error> {
        if c[0] & 0x80 != 0 {
            return Err(Error::Point("bit 255 set"));
        }
        let parity = c[0] & 0x40 != 0;
        let mut yb = *c;
        yb[0] &= 0x3f;
        let y = fr_from_be(&yb).map_err(|_| Error::Point("y >= p"))?;
        let y2 = y.square();
        // x^2 = (1 - y^2) / (a - d*y^2)
        let den = (A - D * y2)
            .inverse()
            .ok_or(Error::Point("no x for this y"))?;
        let x2 = (Fr::ONE - y2) * den;
        let mut x = x2.sqrt().ok_or(Error::Point("not on the curve"))?;
        if x.into_bigint().is_odd() != parity {
            if x == Fr::ZERO {
                return Err(Error::Point("non-canonical zero x"));
            }
            x = -x;
        }
        Ok(Point { x, y })
    }

    /// Reduced twisted Edwards (gnark) coordinates: `x * (-f)`, y unchanged.
    pub fn to_rte(&self) -> (Fr, Fr) {
        (self.x * NEG_F, self.y)
    }

    pub fn from_rte(x: Fr, y: Fr) -> Point {
        let inv = NEG_F.inverse().unwrap_or(Fr::ZERO);
        Point { x: x * inv, y }
    }

    /// Canonical, on-curve point from BE coordinates.
    pub fn from_be(x: &[u8; 32], y: &[u8; 32]) -> Result<Point, Error> {
        let p = Point {
            x: fr_from_be(x)?,
            y: fr_from_be(y)?,
        };
        if !p.is_on_curve() {
            return Err(Error::Point("not on the curve"));
        }
        Ok(p)
    }
}

#[derive(Serialize, Deserialize)]
struct PointHex {
    x: String,
    y: String,
}

impl Serialize for Point {
    fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        PointHex {
            x: format!("0x{}", hex::encode(fr_to_be(&self.x))),
            y: format!("0x{}", hex::encode(fr_to_be(&self.y))),
        }
        .serialize(s)
    }
}

impl<'de> Deserialize<'de> for Point {
    fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        use serde::de::Error as _;
        let h = PointHex::deserialize(d)?;
        let x = hex32(&h.x).map_err(D::Error::custom)?;
        let y = hex32(&h.y).map_err(D::Error::custom)?;
        Point::from_be(&x, &y).map_err(D::Error::custom)
    }
}

/// `0x`-optional hex of exactly 32 bytes.
pub(crate) fn hex32(s: &str) -> Result<[u8; 32], Error> {
    let h = s.strip_prefix("0x").unwrap_or(s);
    let mut out = [0u8; 32];
    hex::decode_to_slice(h, &mut out).map_err(|_| Error::Input("expected 32-byte hex".into()))?;
    Ok(out)
}
